<?php

use Illuminate\Database\Seeder;

class ShopsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('shops')->truncate();
        DB::table('shops')->insert([
        	[
        		'name'=>'nullshop',
        		'station'=>'station0',
        		'chunithm'=>'0',
        		'far'=>'0',
        		'prefecture'=>'ibaraki',
        		'city'=>'mito',
        		'maimai'=>'0',
        		'voltex'=>'0',
        		'jubeat'=>'0',
        		'coaster'=>'0',
        	],
        	[
        		'name'=>'アドアーズ　上野アメ横店',
        		'station'=>'JR上野駅',
                'far'=>'20',
                'prefecture'=>'tokyo',
                'city'=>'ueno',
        		'chunithm'=>'1',
        		'maimai'=>'0',
        		'voltex'=>'0',
        		'jubeat'=>'1',
        		'coaster'=>'0',
        	],
            [
                'name'=>'SEGA秋葉原1号店',
                'station'=>'秋葉原駅',
                'far'=>'10',
                'prefecture'=>'tokyo',
                'city'=>'akihabara',
                'chunithm'=>'1',
                'maimai'=>'1',
                'voltex'=>'0',
                'jubeat'=>'0',
                'coaster'=>'0',
            ],
            [
                'name'=>'SEGA秋葉原2号店',
                'station'=>'秋葉原駅',
                'far'=>'10',
                'prefecture'=>'tokyo',
                'city'=>'akihabara',
                'chunithm'=>'1',
                'maimai'=>'1',
                'voltex'=>'0',
                'jubeat'=>'0',
                'coaster'=>'0',
            ],
            [
                'name'=>'SEGA秋葉原3号店',
                'station'=>'秋葉原駅',
                'far'=>'10',
                'prefecture'=>'tokyo',
                'city'=>'akihabara',
                'chunithm'=>'1',
                'maimai'=>'1',
                'voltex'=>'1',
                'jubeat'=>'1',
                'coaster'=>'0',
            ],
            [
                'name'=>'SEGA秋葉原4号店',
                'station'=>'秋葉原駅',
                'far'=>'10',
                'prefecture'=>'tokyo',
                'city'=>'akihabara',
                'chunithm'=>'1',
                'maimai'=>'1',
                'voltex'=>'0',
                'jubeat'=>'0',
                'coaster'=>'0',
            ],
            [
                'name'=>'ゲームパニックつくば',
                'station'=>'荒川沖駅',
                'far'=>'10',
                'prefecture'=>'ibaraki',
                'city'=>'thuchiura',
                'chunithm'=>'4',
                'maimai'=>'4',
                'voltex'=>'1',
                'jubeat'=>'3',
                'coaster'=>'2',
            ],
            [
                'name'=>'ゲームセンターガリバー',
                'station'=>'柏駅',
                'far'=>'10',
                'prefecture'=>'chiba',
                'city'=>'kashiwa',
                'chunithm'=>'3',
                'maimai'=>'2',
                'voltex'=>'2',
                'jubeat'=>'3',
                'coaster'=>'0',
            ],
            [
                'name'=>'ハイテクセガ柏店',
                'station'=>'柏駅',
                'far'=>'10',
                'prefecture'=>'chiba',
                'city'=>'kashiwa',
                'chunithm'=>'4',
                'maimai'=>'1',
                'voltex'=>'1',
                'jubeat'=>'0',
                'coaster'=>'0',
            ],
        ]);
    }
}
